import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import { 
  CheckSquare, 
  Square, 
  Clock, 
  Calendar, 
  UserCheck, 
  Plus, 
  Filter, 
  CheckCircle2, 
  AlertTriangle,
  ChevronRight
} from 'lucide-react';
import { Task } from '../types';
import { PageHeader } from '../components/PageHeader';

export const TasksView: React.FC = () => {
  const {
    tasks,
    currentUser,
    toggleTaskComplete,
    setSelectedStudentId,
    lang,
    t,
    showToast
  } = useApp();

  const [activeFilter, setActiveFilter] = useState<'my' | 'all' | 'due_today'>('my');

  const filteredTasks = tasks.filter((t) => {
    if (activeFilter === 'my') return t.assignedToId === currentUser.id;
    if (activeFilter === 'due_today') return t.dueDate === '2026-09-30';
    return true;
  });

  return (
    <div className="space-y-4 w-full">
      {/* Shared Page Header */}
      <PageHeader
        title={lang === 'bn' ? 'দৈনিক কাজের তালিকা ও জরুরি ফলো-আপ' : 'Daily Action Items & Follow-up Checklist'}
        description={lang === 'bn' ? 'শিক্ষার্থী পাইপলাইন ও ডকুমেন্টের ভিত্তিতে স্বয়ংক্রিয়ভাবে তৈরি হওয়া টাস্ক' : 'Tasks automatically generated by pipeline milestones and intake deadlines'}
        badge={`${filteredTasks.length} Tasks`}
      >
        {/* Tab Filters */}
        <div className="flex items-center bg-white/5 rounded-xl p-1 border border-white/10 text-xs">
          <button
            onClick={() => setActiveFilter('my')}
            className={`px-3 py-1.5 rounded-lg transition font-semibold ${
              activeFilter === 'my' ? 'bg-[#1EC1CB] text-[#1C1C28]' : 'text-white/60 hover:text-white'
            }`}
          >
            My Tasks
          </button>
          <button
            onClick={() => setActiveFilter('due_today')}
            className={`px-3 py-1.5 rounded-lg transition font-semibold ${
              activeFilter === 'due_today' ? 'bg-[#1EC1CB] text-[#1C1C28]' : 'text-white/60 hover:text-white'
            }`}
          >
            Due Today
          </button>
          <button
            onClick={() => setActiveFilter('all')}
            className={`px-3 py-1.5 rounded-lg transition font-semibold ${
              activeFilter === 'all' ? 'bg-[#1EC1CB] text-[#1C1C28]' : 'text-white/60 hover:text-white'
            }`}
          >
            Team Tasks
          </button>
        </div>
      </PageHeader>

      {/* Task List */}
      <div className="glass-panel border border-white/10 rounded-2xl overflow-hidden divide-y divide-white/5">
        {filteredTasks.length === 0 ? (
          <div className="p-8 text-center text-xs text-white/40">
            All caught up! No active tasks matching your filter.
          </div>
        ) : (
          filteredTasks.map((task) => (
            <div
              key={task.id}
              className={`p-4 flex items-center justify-between gap-4 transition hover:bg-white/[0.03] ${
                task.completed ? 'opacity-50' : ''
              }`}
            >
              <div className="flex items-start gap-3 flex-1">
                <button
                  onClick={() => toggleTaskComplete(task.id)}
                  className="mt-0.5 text-white/40 hover:text-[#1EC1CB] transition cursor-pointer"
                >
                  {task.completed ? (
                    <CheckSquare className="w-5 h-5 text-emerald-400" />
                  ) : (
                    <Square className="w-5 h-5" />
                  )}
                </button>

                <div className="space-y-1">
                  <h4 className={`text-xs font-bold ${task.completed ? 'line-through text-white/50' : 'text-white'}`}>
                    {lang === 'bn' ? task.titleBn : task.title}
                  </h4>
                  <div className="flex items-center gap-3 text-[11px] text-white/40 flex-wrap">
                    <span className="flex items-center gap-1 font-mono text-white/70">
                      <Calendar className="w-3 h-3 text-[#1EC1CB]" />
                      Due: {task.dueDate}
                    </span>
                    <span>•</span>
                    <span className="flex items-center gap-1">
                      <UserCheck className="w-3 h-3 text-white/40" />
                      Assigned: {task.assignedToName}
                    </span>
                    {task.studentName && (
                      <>
                        <span>•</span>
                        <button
                          onClick={() => task.studentId && setSelectedStudentId(task.studentId)}
                          className="text-[#1EC1CB] hover:underline font-semibold"
                        >
                          Student: {task.studentName}
                        </button>
                      </>
                    )}
                  </div>
                </div>
              </div>

              <div className="flex items-center gap-2">
                <span className={`text-[10px] px-2 py-0.5 rounded-full font-semibold uppercase ${
                  task.priority === 'high' ? 'bg-red-500/20 text-red-300 border border-red-500/30' :
                  'bg-blue-500/20 text-blue-300 border border-blue-500/30'
                }`}>
                  {task.priority}
                </span>

                {task.studentId && (
                  <button
                    onClick={() => setSelectedStudentId(task.studentId!)}
                    className="p-1.5 rounded-lg bg-white/5 text-white/60 hover:text-white transition"
                    title="Open Student Profile"
                  >
                    <ChevronRight className="w-4 h-4" />
                  </button>
                )}
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
};
